---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах 
implicit:
  - рейтинг товара должен быть от 0.0 до 10.0 с шагом 0.1
  - цена товара со скидкой и без должна быть положительной
  - цена товара без скидки должна быть больше, чем со скидкой
  - Название товара должно состоять из русских и(или) латинских букв, цифр,других символов, содержать реально существующие слова и наименования
